##########################
# -- Required options -- #
##########################

# Name of Website
title: Cat and Witch Games

# Your Name
author: Cat and Witch Games

################
# --- Logo --- #
################
avatar: "/assets/img/avatar.png"

###########################
# -- General Options -- ###
###########################
excerpt_length: 10000
feed_show_excerpt: true

# Site meta-data
email: witch@catandwitchgames.com
description: >- # this means to ignore newlines until "baseurl:"
  Indie game studio specializing in point-and-click adventures.             
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://catandwitchgames.com" 

#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "witch@catandwitchgames.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
#  facebook: deanattali
#  github: daattali
#  twitter: daattali
#  patreon: DeanAttali
#  youtube: c/daattali
#  medium: yourname
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
#  discord: invite/invite_code or users/userid 
#  kaggle: yourname
#  hackerrank: yourname


# Build settings
remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
